### ISSUE TITLE
Переход с compile на implementation в build.gradle

### ISSUE THREAD

**Issue by vovka-s** [yandexmobile/metrica-plugin-cordova#29]
Привет!
Сегодня после обновления Градла словил ошибку при сборке проекта
`compile` давно был deprecated, а из gradle 7.x его уже удалили
Пофиксил переходом на `implementation`

```diff
diff --git a/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle b/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle
index a96389f..ed3ecef 100644
--- a/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle
+++ b/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle
@@ -12,5 +12,5 @@ repositories{
 }
 
 dependencies {
-	compile 'com.yandex.android:mobmetricalib:3.6.4'
+	implementation 'com.yandex.android:mobmetricalib:3.6.4'
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ghost** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 18823365. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp19.08.2022, 19:36, "vovka-s" ***@***.***>:
Привет!
Сегодня после обновления Градла словил ошибку при сборке проекта
compile давно был deprecated, а из gradle 7.x его уже удалили
Пофиксил переходом на implementation
diff --git a/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle b/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle
index a96389f..ed3ecef 100644
--- a/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle
+++ b/node_modules/yandex-appmetrica-plugin-cordova/platforms/android/build.gradle
@@ -12,5 +12,5 @@ repositories{
 }
 
 dependencies {
-	compile 'com.yandex.android:mobmetricalib:3.6.4'
+	implementation 'com.yandex.android:mobmetricalib:3.6.4'
 }
This issue body was partially generated by patch-package.

**Comment by ghost** [comment]
Плагин Cordova более не поддерживается. Мы не гарантируем его корректную работу.

**Comment by vovka-s** [comment]
> Плагин Cordova более не поддерживается. Мы не гарантируем его корректную работу.

Фикс в одну строчку... Почему бы не залить?

**Comment by trinitiwowka** [comment]
> > Плагин Cordova более не поддерживается. Мы не гарантируем его корректную работу.
> 
> Фикс в одну строчку... Почему бы не залить?

Это же Яндекс))) у них все через одно место, можешь склонить проект, положить его куда-то локально и поставить оттуда. если хочешь оставить для других коллег - закомить его как сабпроект но с завязкой под конкретный коммит

в packaje.json будет выглядеть так. 
    "yandex-appmetrica-plugin-cordova": "file:local-plugins/metrica-plugin-cordova"

Ну или форкнуть и указать url к своему гитхаб проекту

**Comment by vovka-s** [comment]
Да я сделал патч через patch-package, он сам накатывается при установке зависимостей. Меня устраивает
Но Яндекса не понял))

**Comment by rusekr** [comment]
> Плагин Cordova более не поддерживается. Мы не гарантируем его корректную работу.

Так обозначьте это хотябы в README у репозитория, чтобы заранее было понятно.

**Comment by AppMetricaOvermindGenius180iq** [comment]
Это обозначено в документации: https://appmetrica.yandex.com/docs/mobile-sdk-dg/plugins/cordova/cordova-plugin.html
