### ISSUE TITLE
Трекинг инсталляций

### ISSUE THREAD

**Issue by artuska** [yandexmobile/metrica-plugin-cordova#7]
А плагин из коробки отсылает данные в аппметрику, чтобы тречить инсталляции? Чтобы я видел,  из какой кампании пришла инсталляция.

Мне, как я понимаю, из Яваскрипта доступны только вот эти конфигурационные параметры — https://tech.yandex.ru/appmetrica/doc/mobile-sdk-dg/concepts/cordova-methods-docpage/

Мне нужно где-то прописывать вот все эти блоки кода (для iOS и Андроида) — https://tech.yandex.ru/appmetrica/doc/mobile-sdk-dg/concepts/ios-operations-docpage/#start-conf — или они уже за меня прописаны из коробки?

**Comment by bamx23** [comment]
Для трекинга установок достаточно активироваться с соответствующим API-ключом(`config.apiKey`).

**Comment by artuska** [comment]
Что-нибудь можно по этому выводу лога сказать? После `deviceready` я запускаю активацию аппметрики с конфигом, всё это вывожу в консоль XCode-дебаггера, т.е., типа, всё работает:

```
2018-04-03 11:29:24.594194+0300 Balu[6458:3335550] MetrikaService initializeMobile
2018-04-03 11:29:24.594369+0300 Balu[6458:3335550] {"apiKey":"0a8e0b38-5444-4d6b-8a1e-a62dcdb82e20","appVersion":"1.0.98","trackLocationEnabled":false,"handleFirstActivationAsUpdateEnabled":false,"sessionTimeout":15,"loggingEnabled":true}
11:29:24:685 YandexMobileMetrica: Set custom app version 1.0.98
11:29:24:686 YandexMobileMetrica: Activated. Version:2.94, Release build 8876
2018-04-03 11:29:24.688322+0300 Balu[6458:3335686] YandexMobileMetrica: Set custom app version 1.0.98
2018-04-03 11:29:24.688473+0300 Balu[6458:3335686] YandexMobileMetrica: Activated. Version:2.94, Release build 8876
```

Это у меня в дебаггере не выводятся последующие эвенты или там и не должно ничего выводиться по поводу эвентов трекинга инсталляций?

А вообще, проблема в том, что в Аппметрику приходят инсталляции, но в категорию «Не определено» — т.е. почему-то кордововская аппметрика что-то не может до конца определить, чтобы положить инсталляцию в нужный трекер от нужной кампании, всё скидывает в «Не определено».

Пробовал менять `handleFirstActivationAsUpdateEnabled` на `true` и на `false` — безрезультатно.

**Comment by bamx23** [comment]
По этому логу всё в порядке, АппМетрика активировалась штатно. Логика аттрибуции в большей степени на сервере, так что в лог по этому поводу ничего не выводится.
`handleFirstActivationAsUpdateEnabled == true` вообще не будет считать установку новой, так что Вам этот параметр в данном случае трогать не надо. 
Аттрибуция сама по себе может занимать время. Если проблема будет продолжаться обратитесь в поддержку, чтобы изучить конкретно Ваше приложение.
А ещё у нас есть чат: https://t.me/appmetrica_chat

**Comment by artuska** [comment]
Спасибо! Чат это вообще потрясающе, пойду туда :)
